---
# nginx file for cs-cart

- name: Update apt packages
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Copy Nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart Nginx Service

- name: Ensure Nginx service is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes


# task file for cs-cart
- import_tasks: php7.4-fpm.yml
- import_tasks: mariadb.yml
