---
# php7.4 file for cs-cart

- name: Add PHP 7.4 repository
  apt_repository:
    repo: ppa:ondrej/php
  when: ansible_distribution == 'Ubuntu'

- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install PHP 7.4 and required extensions
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php7.4-fpm
    - php7.4-common
    - php7.4-dom
    - php7.4-intl
    - php7.4-mysql
    - php7.4-xml
    - php7.4-xmlrpc
    - php7.4-curl
    - php7.4-gd
    - php7.4-imagick
    - php7.4-cli
    - php7.4-dev
    - php7.4-imap
    - php7.4-mbstring
    - php7.4-soap
    - php7.4-zip
    - php7.4-bcmath
    - php7.4-igbinary
    - php7.4-redis
  notify: Restart PHP

- name: Start and enable PHP 7.4-FPM service
  service:
    name: php7.4-fpm
    state: started
    enabled: yes
